
server:
  port: 8000

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT}
  profiles:
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    #    url: jdbc:mysql://localhost:3306/tenten?serverTimezone=Asia/Seoul
    #
    username: ${DATABASE_ID}
    password: ${DATABASE_PASSWORD}
    # JPA
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        #        format_sql: true
        default_batch_fetch_size: 100 #성능 최적화

jwt:
  secretKey: ${JWT_SECRET}
  access:
    expiration: 36000000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization_refresh