export { default as Main } from "./main/Main";
export { default as Exchange } from "./exchange/Exchange";
export { default as BottomNav } from "./common/BottomNav";
export { default as MessageList } from "./message/MessageList";
// export { default as Vote } from './vote';
// export { default as Exchanges } from './Exchanges';
export * from "./news";
// export { default as Quiz } from './quiz/';
export { default as Mypage } from "./mypage/Mypage";
export { default as TobTab } from "./common/TobTab";
