export { default as Main } from "./main/Main";
export { default as Exchange } from "./exchange/Exchange";
export { default as ExchangeCoin } from "./exchange/ExchangeCoin";
export { default as BottomNav } from "./common/BottomNav";
export { default as MessageList } from "./message/MessageList";
export { default as MessageContent } from "./message/MessageContent";
export { default as Question } from "./vote/Question";
export { default as Candidates } from "./vote/Candidates";
export { default as CandidatesSearch } from "./vote/CandidatesSearch";
// export { default as Vote } from './vote';
// export { default as Exchanges } from './Exchanges';
export * from "./news";
// export { default as Quiz } from './quiz/';
export { default as Profile } from "./mypage/Profile";
export { default as History } from "./mypage/History";
export { default as Top3 } from "./mypage/Top3";
export { default as MyFriends } from "./mypage/MyFriends";
export { default as RecommendFriends } from "./mypage/RecommendFriends";
export { default as RequestQuestion } from "./mypage/RequestQuestion";
export { default as Logout } from "./mypage/Logout";
export { default as DeleteAccount } from "./mypage/DeleteAccount";
export { default as TobTab } from "./common/TobTab";
